import * as monaco from "monaco-editor";

const Kind = monaco.languages.CompletionItemKind;

/**
 * Monaco marks `range` required on CompletionItem, but the provider should set it from the
 * editor position when merging static items with dynamic results.
 */
export type OracleStaticCompletionItem = Omit<
  monaco.languages.CompletionItem,
  "range"
> & { range?: monaco.languages.CompletionItem["range"] };

/** Multi-word and special insert text for common SQL phrases. */
function kw(
  label: string,
  extra?: { insertText?: string; detail?: string; documentation?: string }
): OracleStaticCompletionItem {
  return {
    label,
    kind: Kind.Keyword,
    insertText: extra?.insertText ?? `${label} `,
    detail: extra?.detail,
    documentation: extra?.documentation,
    sortText: `0_${label}`,
  };
}

function fn(
  label: string,
  extra?: { detail?: string; documentation?: string }
): OracleStaticCompletionItem {
  return {
    label,
    kind: Kind.Function,
    insertText: `${label} `,
    detail: extra?.detail,
    documentation: extra?.documentation,
    sortText: `1_${label}`,
  };
}

function typ(label: string): OracleStaticCompletionItem {
  return {
    label,
    kind: Kind.Class,
    insertText: `${label} `,
    sortText: `2_${label}`,
  };
}

/** Single-token SQL / Oracle keywords (uppercase labels), deduped. */
const SQL_KEYWORD_TOKENS: readonly string[] = [
  "SELECT",
  "FROM",
  "WHERE",
  "AND",
  "OR",
  "NOT",
  "NULL",
  "TRUE",
  "FALSE",
  "IS",
  "IN",
  "ANY",
  "ALL",
  "SOME",
  "EXISTS",
  "BETWEEN",
  "LIKE",
  "ESCAPE",
  "DISTINCT",
  "UNIQUE",
  "AS",
  "ASC",
  "DESC",
  "NULLS",
  "FIRST",
  "LAST",
  "BY",
  "HAVING",
  "WITH",
  "RECURSIVE",
  "MATCH",
  "RECOGNIZE",
  "PATTERN",
  "DEFINE",
  "MEASURES",
  "ONE",
  "MANY",
  "ROW",
  "ROWS",
  "ONLY",
  "PER",
  "MATCHES",
  "JOIN",
  "INNER",
  "LEFT",
  "RIGHT",
  "FULL",
  "CROSS",
  "OUTER",
  "NATURAL",
  "ON",
  "USING",
  "UNION",
  "INTERSECT",
  "MINUS",
  "EXCEPT",
  "CASE",
  "WHEN",
  "THEN",
  "ELSE",
  "END",
  "CAST",
  "MULTISET",
  "CURSOR",
  "OVER",
  "PARTITION",
  "WINDOW",
  "RANGE",
  "PRECEDING",
  "FOLLOWING",
  "UNBOUNDED",
  "CURRENT",
  "INSERT",
  "INTO",
  "VALUES",
  "UPDATE",
  "SET",
  "DELETE",
  "MERGE",
  "TRUNCATE",
  "COMMIT",
  "ROLLBACK",
  "SAVEPOINT",
  "WORK",
  "FORCE",
  "WAIT",
  "NOWAIT",
  "SKIP",
  "LOCKED",
  "FOR",
  "OF",
  "SHARE",
  "MODE",
  "CREATE",
  "ALTER",
  "DROP",
  "RENAME",
  "TRIGGER",
  "PROCEDURE",
  "FUNCTION",
  "PACKAGE",
  "BODY",
  "TYPE",
  "TABLE",
  "VIEW",
  "MATERIALIZED",
  "SEQUENCE",
  "INDEX",
  "SYNONYM",
  "DATABASE",
  "LINK",
  "USER",
  "ROLE",
  "PROFILE",
  "GRANT",
  "REVOKE",
  "TO",
  "PUBLIC",
  "IDENTIFIED",
  "DEFAULT",
  "TABLESPACE",
  "CONSTRAINT",
  "PRIMARY",
  "KEY",
  "FOREIGN",
  "REFERENCES",
  "CHECK",
  "CASCADE",
  "RESTRICT",
  "NO",
  "ACTION",
  "DEFERRABLE",
  "INITIALLY",
  "DEFERRED",
  "IMMEDIATE",
  "ENABLE",
  "DISABLE",
  "NOVALIDATE",
  "RELY",
  "NORELY",
  "CONSTRAINTS",
  "NOSORT",
  "REVERSE",
  "ONLINE",
  "OFFLINE",
  "MONITORING",
  "NOMONITORING",
  "PARALLEL",
  "NOPARALLEL",
  "COMPRESS",
  "NOCOMPRESS",
  "LOGGING",
  "NOLOGGING",
  "STORAGE",
  "PCTFREE",
  "PCTUSED",
  "INITRANS",
  "MAXTRANS",
  "PRIOR",
  "START",
  "CONNECT",
  "NOCYCLE",
  "LEVEL",
  "SYS_CONNECT_BY_PATH",
  "FLASHBACK",
  "VERSIONS",
  "SCN",
  "TIMESTAMP",
  "CONTAINER",
  "PDB",
  "SEED",
  "REBUILD",
  "PIVOT",
  "UNPIVOT",
  "SAMPLE",
  "SUBPARTITION",
  "SUBPARTITIONS",
  "LOB",
  "STORE",
  "ROWDEPENDENCIES",
  "NOROWDEPENDENCIES",
  "RESULT_CACHE",
  "READ",
  "WRITE",
  "SKIP_UNUSABLE_INDEX",
  "CHANGE_DUPKEY_ERROR_INDEX",
  "IGNORE_ROW_ON_DUPKEY_INDEX",
  "RETURNING",
  "BULK",
  "COLLECT",
  "LIMIT",
  "RETURN",
  "LOG",
  "ERRORS",
  "REJECT",
  "TAG",
  "NEXTVAL",
  "CURRVAL",
  "IDENTITY",
  "GENERATED",
  "ALWAYS",
  "VIRTUAL",
  "VISIBLE",
  "INVISIBLE",
  "OFFSET",
];

/** Multi-word phrases (labels with spaces). */
const SQL_KEYWORD_PHRASES: readonly OracleStaticCompletionItem[] = [
  kw("GROUP BY", { insertText: "GROUP BY " }),
  kw("ORDER BY", { insertText: "ORDER BY " }),
  kw("CONNECT BY", { insertText: "CONNECT BY " }),
  kw("START WITH", { insertText: "START WITH " }),
  kw("FETCH FIRST", { insertText: "FETCH FIRST " }),
  kw("ROWS ONLY", { insertText: "ROWS ONLY " }),
  kw("INSERT ALL", { insertText: "INSERT ALL " }),
  kw("INSERT FIRST", { insertText: "INSERT FIRST " }),
  kw("WHEN MATCHED", { insertText: "WHEN MATCHED " }),
  kw("WHEN NOT MATCHED", { insertText: "WHEN NOT MATCHED " }),
  kw("PARTITION BY", { insertText: "PARTITION BY " }),
  kw("NULLS FIRST", { insertText: "NULLS FIRST " }),
  kw("NULLS LAST", { insertText: "NULLS LAST " }),
  kw("FOR UPDATE", { insertText: "FOR UPDATE " }),
  kw("ROWNUM", {
    detail: "Pseudocolumn",
    documentation: "Limits rows in Oracle (e.g. WHERE ROWNUM <= 100).",
  }),
  kw("ROWID", {
    detail: "Pseudocolumn",
    documentation: "Physical row address for a table row.",
  }),
];

const PLSQL_KEYWORD_TOKENS: readonly string[] = [
  "DECLARE",
  "BEGIN",
  "EXCEPTION",
  "RAISE",
  "LOOP",
  "WHILE",
  "FOR",
  "IF",
  "ELSIF",
  "GOTO",
  "EXIT",
  "CONTINUE",
  "OPEN",
  "CLOSE",
  "FETCH",
  "INTO",
  "USING",
  "OUT",
  "IN",
  "NOCOPY",
  "PIPE",
  "ROW",
  "ROWTYPE",
  "%TYPE",
  "%ROWTYPE",
  "RECORD",
  "TABLE",
  "OF",
  "VARRAY",
  "INDEX",
  "BY",
  "PLS_INTEGER",
  "BINARY_INTEGER",
  "NATURAL",
  "NATURALN",
  "POSITIVE",
  "POSITIVEN",
  "SIGNTYPE",
  "SIMPLE_INTEGER",
  "STRING",
  "BOOLEAN",
  "LONG",
  "RAW",
  "SUBTYPE",
  "CONSTANT",
  "NOT",
  "NULL",
  "DEFAULT",
  "EXECUTE",
  "IMMEDIATE",
  "RETURNING",
  "BULK",
  "COLLECT",
  "FORALL",
  "INDICES",
  "VALUES",
  "SAVE",
  "EXCEPTIONS",
  "AUTONOMOUS_TRANSACTION",
  "SERIALLY_REUSABLE",
  "INLINE",
  "RESULT_CACHE",
  "ACCESSIBLE",
  "DETERMINISTIC",
  "PIPELINED",
  "PARALLEL_ENABLE",
  "AGGREGATE",
  "USING",
  "RELIES_ON",
  "PRAGMA",
  "EXCEPTION_INIT",
  "SUPPRESS_WARNINGS",
  "COVERAGE",
  "INTERFACE",
];

const ORACLE_FUNCTIONS: readonly OracleStaticCompletionItem[] = [
  fn("NVL", {
    detail: "NVL(expr, replacement)",
    documentation: "Returns replacement if expr is NULL; otherwise expr.",
  }),
  fn("NVL2", {
    detail: "NVL2(expr, v1, v2)",
    documentation:
      "Returns v1 if expr is not NULL; otherwise v2.",
  }),
  fn("DECODE", {
    detail: "DECODE(expr, search, result [, ...] [, default])",
    documentation: "Compares expr to search values; returns matching result.",
  }),
  fn("COALESCE", {
    detail: "COALESCE(expr1, expr2, ...)",
    documentation: "First non-NULL argument.",
  }),
  fn("NULLIF", { detail: "NULLIF(expr1, expr2)" }),
  fn("TO_CHAR", {
    detail: "TO_CHAR(date|number [, fmt])",
    documentation: "Convert to VARCHAR2.",
  }),
  fn("TO_DATE", {
    detail: "TO_DATE(char [, fmt])",
    documentation: "Convert string to DATE.",
  }),
  fn("TO_NUMBER", { detail: "TO_NUMBER(char [, fmt])" }),
  fn("TO_TIMESTAMP", { detail: "TO_TIMESTAMP(char [, fmt])" }),
  fn("TO_TIMESTAMP_TZ", { detail: "TO_TIMESTAMP_TZ(char [, fmt])" }),
  fn("TO_CLOB", { detail: "TO_CLOB(expr)" }),
  fn("TO_NCLOB", { detail: "TO_NCLOB(expr)" }),
  fn("TO_BLOB", { detail: "TO_BLOB(r)" }),
  fn("SUBSTR", { detail: "SUBSTR(str, pos [, len])" }),
  fn("LENGTH", { detail: "LENGTH(str)" }),
  fn("LENGTHB", { detail: "LENGTHB(str)" }),
  fn("INSTR", { detail: "INSTR(str, sub [, pos [, nth]])" }),
  fn("TRIM", { detail: "TRIM([[LEADING|TRAILING|BOTH] trim FROM] str)" }),
  fn("LTRIM", { detail: "LTRIM(str [, set])" }),
  fn("RTRIM", { detail: "RTRIM(str [, set])" }),
  fn("LPAD", { detail: "LPAD(str, len [, pad])" }),
  fn("RPAD", { detail: "RPAD(str, len [, pad])" }),
  fn("REPLACE", { detail: "REPLACE(str, search [, rep])" }),
  fn("TRANSLATE", { detail: "TRANSLATE(str, from, to)" }),
  fn("UPPER", { detail: "UPPER(str)" }),
  fn("LOWER", { detail: "LOWER(str)" }),
  fn("INITCAP", { detail: "INITCAP(str)" }),
  fn("CONCAT", { detail: "CONCAT(a, b)" }),
  fn("CHR", { detail: "CHR(n)" }),
  fn("ASCII", { detail: "ASCII(char)" }),
  fn("NCHR", { detail: "NCHR(n)" }),
  fn("DUMP", { detail: "DUMP(expr [, fmt [, pos [, len]]])" }),
  fn("REGEXP_SUBSTR", {
    detail: "REGEXP_SUBSTR(str, pattern [, pos [, occ [, ox [, subexpr]]]])",
  }),
  fn("REGEXP_REPLACE", {
    detail: "REGEXP_REPLACE(str, pattern [, rep [, pos [, occ [, m]]]])",
  }),
  fn("REGEXP_INSTR", {
    detail: "REGEXP_INSTR(str, pattern [, pos [, occ [, ret [, ox [, sx]]]]])",
  }),
  fn("REGEXP_COUNT", { detail: "REGEXP_COUNT(str, pattern [, pos [, ox]])" }),
  fn("REGEXP_LIKE", { detail: "REGEXP_LIKE(src, pattern [, flags])" }),
  fn("ABS", { detail: "ABS(n)" }),
  fn("CEIL", { detail: "CEIL(n)" }),
  fn("FLOOR", { detail: "FLOOR(n)" }),
  fn("MOD", { detail: "MOD(m, n)" }),
  fn("POWER", { detail: "POWER(m, n)" }),
  fn("ROUND", { detail: "ROUND(n [, p])" }),
  fn("TRUNC", { detail: "TRUNC(date|number [, p])" }),
  fn("SIGN", { detail: "SIGN(n)" }),
  fn("SQRT", { detail: "SQRT(n)" }),
  fn("EXP", { detail: "EXP(n)" }),
  fn("LN", { detail: "LN(n)" }),
  fn("LOG", { detail: "LOG(base, n)" }),
  fn("GREATEST", { detail: "GREATEST(expr, ...)" }),
  fn("LEAST", { detail: "LEAST(expr, ...)" }),
  fn("AVG", { detail: "AVG(expr)" }),
  fn("COUNT", { detail: "COUNT(expr|*)" }),
  fn("MAX", { detail: "MAX(expr)" }),
  fn("MIN", { detail: "MIN(expr)" }),
  fn("SUM", { detail: "SUM(expr)" }),
  fn("STDDEV", { detail: "STDDEV(expr)" }),
  fn("VARIANCE", { detail: "VARIANCE(expr)" }),
  fn("MEDIAN", { detail: "MEDIAN(expr)" }),
  fn("LISTAGG", {
    detail: "LISTAGG(expr [, delim]) WITHIN GROUP (ORDER BY ...)",
  }),
  fn("RANK", { detail: "RANK() OVER (...)" }),
  fn("DENSE_RANK", { detail: "DENSE_RANK() OVER (...)" }),
  fn("ROW_NUMBER", { detail: "ROW_NUMBER() OVER (...)" }),
  fn("LAG", { detail: "LAG(expr [, off [, def]]) [, IGNORE NULLS]" }),
  fn("LEAD", { detail: "LEAD(expr [, off [, def]]) [, IGNORE NULLS]" }),
  fn("FIRST_VALUE", { detail: "FIRST_VALUE(expr) OVER (...)" }),
  fn("LAST_VALUE", { detail: "LAST_VALUE(expr) OVER (...)" }),
  fn("NTH_VALUE", { detail: "NTH_VALUE(expr, n) [, FROM ...] OVER (...)" }),
  fn("NTILE", { detail: "NTILE(n) OVER (...)" }),
  fn("RATIO_TO_REPORT", { detail: "RATIO_TO_REPORT(expr) OVER (...)" }),
  fn("PERCENT_RANK", { detail: "PERCENT_RANK() OVER (...)" }),
  fn("CUME_DIST", { detail: "CUME_DIST() OVER (...)" }),
  fn("PERCENTILE_CONT", {
    detail: "PERCENTILE_CONT(p) WITHIN GROUP (ORDER BY ...)",
  }),
  fn("PERCENTILE_DISC", {
    detail: "PERCENTILE_DISC(p) WITHIN GROUP (ORDER BY ...)",
  }),
  fn("ADD_MONTHS", { detail: "ADD_MONTHS(date, n)" }),
  fn("MONTHS_BETWEEN", { detail: "MONTHS_BETWEEN(d1, d2)" }),
  fn("NEXT_DAY", { detail: "NEXT_DAY(date, weekday)" }),
  fn("LAST_DAY", { detail: "LAST_DAY(date)" }),
  fn("EXTRACT", { detail: "EXTRACT(part FROM expr)" }),
  fn("SYSDATE", { detail: "Current database date/time" }),
  fn("SYSTIMESTAMP", { detail: "Current TIMESTAMP WITH TIME ZONE" }),
  fn("CURRENT_DATE", {}),
  fn("CURRENT_TIMESTAMP", {}),
  fn("LOCALTIMESTAMP", {}),
  fn("SESSIONTIMEZONE", {}),
  fn("DBTIMEZONE", {}),
  fn("FROM_TZ", { detail: "FROM_TZ(ts, tz)" }),
  fn("TZ_OFFSET", { detail: "TZ_OFFSET(tz)" }),
  fn("NUMTODSINTERVAL", { detail: "NUMTODSINTERVAL(n, unit)" }),
  fn("NUMTOYMINTERVAL", { detail: "NUMTOYMINTERVAL(n, unit)" }),
  fn("SYS_GUID", { detail: "Global unique identifier" }),
  fn("UID", { detail: "Numeric user id" }),
  fn("USER", { detail: "Current session user name" }),
  fn("USERENV", { detail: "USERENV(param)" }),
  fn("SYS_CONTEXT", { detail: "SYS_CONTEXT(namespace, attr)" }),
  fn("RAWTOHEX", { detail: "RAWTOHEX(raw)" }),
  fn("HEXTORAW", { detail: "HEXTORAW(hex)" }),
  fn("EMPTY_BLOB", {}),
  fn("EMPTY_CLOB", {}),
  fn("STANDARD_HASH", { detail: "STANDARD_HASH(expr [, algo])" }),
  fn("ORA_HASH", { detail: "ORA_HASH(expr [, max [, seed]])" }),
  fn("VSIZE", { detail: "VSIZE(expr)" }),
  fn("JSON_VALUE", { detail: "JSON_VALUE(expr, path ...)" }),
  fn("JSON_QUERY", { detail: "JSON_QUERY(expr, path ...)" }),
  fn("JSON_OBJECT", {}),
  fn("JSON_ARRAY", {}),
  fn("JSON_ARRAYAGG", {}),
  fn("JSON_OBJECTAGG", {}),
  fn("TREAT", { detail: "TREAT(ref AS type)" }),
  fn("REF", { detail: "REF(table_alias)" }),
  fn("VALUE", { detail: "VALUE(collection_var)" }),
];

const ORACLE_TYPES: readonly string[] = [
  "VARCHAR2",
  "NVARCHAR2",
  "CHAR",
  "NCHAR",
  "NUMBER",
  "FLOAT",
  "BINARY_FLOAT",
  "BINARY_DOUBLE",
  "INTEGER",
  "INT",
  "SMALLINT",
  "DECIMAL",
  "NUMERIC",
  "DATE",
  "TIMESTAMP",
  "TIMESTAMP WITH TIME ZONE",
  "TIMESTAMP WITH LOCAL TIME ZONE",
  "INTERVAL YEAR TO MONTH",
  "INTERVAL DAY TO SECOND",
  "RAW",
  "LONG RAW",
  "ROWID",
  "UROWID",
  "CLOB",
  "NCLOB",
  "BLOB",
  "BFILE",
  "XMLTYPE",
  "JSON",
  "BOOLEAN",
];

function dedupeKeywords(labels: readonly string[]): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const l of labels) {
    const u = l.toUpperCase();
    if (!seen.has(u)) {
      seen.add(u);
      out.push(l);
    }
  }
  return out;
}

let cache: OracleStaticCompletionItem[] | null = null;

/**
 * All static Oracle SQL / PL-SQL completion items for merging with dynamic schema suggestions.
 * Result is cached for the lifetime of the app.
 */
export function getOracleStaticCompletions(): OracleStaticCompletionItem[] {
  if (cache) {
    return cache;
  }

  const kwTokens = dedupeKeywords([...SQL_KEYWORD_TOKENS, ...PLSQL_KEYWORD_TOKENS]);
  const fromTokens = kwTokens.map((label) =>
    kw(label, { insertText: `${label} ` })
  );

  const labelSet = new Set(
    fromTokens.map((i) => i.label.toString().toUpperCase())
  );
  const phrases = SQL_KEYWORD_PHRASES.filter(
    (p) => !labelSet.has(p.label.toString().toUpperCase())
  );

  const fnLabels = new Set(
    ORACLE_FUNCTIONS.map((f) => f.label.toString().toUpperCase())
  );
  const typeItems = ORACLE_TYPES.map((t) => typ(t)).filter((t) => {
    const u = t.label.toString().toUpperCase();
    return !fnLabels.has(u) && !labelSet.has(u);
  });

  cache = [...fromTokens, ...phrases, ...ORACLE_FUNCTIONS, ...typeItems];
  return cache;
}
