// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelQuery(arg1) {
  return window['go']['main']['App']['CancelQuery'](arg1);
}

export function Commit(arg1) {
  return window['go']['main']['App']['Commit'](arg1);
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['main']['App']['Disconnect'](arg1);
}

export function ExecuteSQL(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteSQL'](arg1, arg2, arg3);
}

export function GetActiveConnectionID() {
  return window['go']['main']['App']['GetActiveConnectionID']();
}

export function GetColumns(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetColumns'](arg1, arg2, arg3);
}

export function GetConstraints(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetConstraints'](arg1, arg2, arg3);
}

export function GetDDL(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetDDL'](arg1, arg2, arg3, arg4);
}

export function GetFunctions(arg1, arg2) {
  return window['go']['main']['App']['GetFunctions'](arg1, arg2);
}

export function GetIndexes(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetIndexes'](arg1, arg2, arg3);
}

export function GetMaterializedViews(arg1, arg2) {
  return window['go']['main']['App']['GetMaterializedViews'](arg1, arg2);
}

export function GetPackages(arg1, arg2) {
  return window['go']['main']['App']['GetPackages'](arg1, arg2);
}

export function GetProcedures(arg1, arg2) {
  return window['go']['main']['App']['GetProcedures'](arg1, arg2);
}

export function GetSavedConnections() {
  return window['go']['main']['App']['GetSavedConnections']();
}

export function GetSchemas(arg1) {
  return window['go']['main']['App']['GetSchemas'](arg1);
}

export function GetSequences(arg1, arg2) {
  return window['go']['main']['App']['GetSequences'](arg1, arg2);
}

export function GetSynonyms(arg1, arg2) {
  return window['go']['main']['App']['GetSynonyms'](arg1, arg2);
}

export function GetTables(arg1, arg2) {
  return window['go']['main']['App']['GetTables'](arg1, arg2);
}

export function GetTriggersForSchema(arg1, arg2) {
  return window['go']['main']['App']['GetTriggersForSchema'](arg1, arg2);
}

export function GetTriggersForTable(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTriggersForTable'](arg1, arg2, arg3);
}

export function GetTypes(arg1, arg2) {
  return window['go']['main']['App']['GetTypes'](arg1, arg2);
}

export function GetViews(arg1, arg2) {
  return window['go']['main']['App']['GetViews'](arg1, arg2);
}

export function Rollback(arg1) {
  return window['go']['main']['App']['Rollback'](arg1);
}

export function SaveConnection(arg1) {
  return window['go']['main']['App']['SaveConnection'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}
