// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function Commit(arg1:string):Promise<void>;

export function Connect(arg1:string):Promise<void>;

export function DeleteConnection(arg1:string):Promise<void>;

export function Disconnect(arg1:string):Promise<void>;

export function ExecuteSQL(arg1:string,arg2:string,arg3:number):Promise<models.QueryResult>;

export function GetActiveConnectionID():Promise<string>;

export function GetSavedConnections():Promise<Array<models.ConnectionConfig>>;

export function Rollback(arg1:string):Promise<void>;

export function SaveConnection(arg1:models.ConnectionConfig):Promise<models.ConnectionConfig>;

export function TestConnection(arg1:models.ConnectionConfig):Promise<string>;
