// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CancelQuery(arg1:string):Promise<void>;

export function Commit(arg1:string):Promise<void>;

export function Connect(arg1:string):Promise<void>;

export function DeleteConnection(arg1:string):Promise<void>;

export function Disconnect(arg1:string):Promise<void>;

export function ExecuteSQL(arg1:string,arg2:string,arg3:number):Promise<models.QueryResult>;

export function GetActiveConnectionID():Promise<string>;

export function GetColumns(arg1:string,arg2:string,arg3:string):Promise<Array<models.ColumnDetail>>;

export function GetConstraints(arg1:string,arg2:string,arg3:string):Promise<Array<models.ConstraintInfo>>;

export function GetDDL(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GetFunctions(arg1:string,arg2:string):Promise<Array<string>>;

export function GetIndexes(arg1:string,arg2:string,arg3:string):Promise<Array<models.IndexInfo>>;

export function GetMaterializedViews(arg1:string,arg2:string):Promise<Array<string>>;

export function GetPackages(arg1:string,arg2:string):Promise<Array<string>>;

export function GetProcedures(arg1:string,arg2:string):Promise<Array<string>>;

export function GetSavedConnections():Promise<Array<models.ConnectionConfig>>;

export function GetSchemas(arg1:string):Promise<Array<string>>;

export function GetSequences(arg1:string,arg2:string):Promise<Array<string>>;

export function GetSynonyms(arg1:string,arg2:string):Promise<Array<string>>;

export function GetTables(arg1:string,arg2:string):Promise<Array<models.TableInfo>>;

export function GetTriggersForSchema(arg1:string,arg2:string):Promise<Array<string>>;

export function GetTriggersForTable(arg1:string,arg2:string,arg3:string):Promise<Array<string>>;

export function GetTypes(arg1:string,arg2:string):Promise<Array<string>>;

export function GetViews(arg1:string,arg2:string):Promise<Array<string>>;

export function Rollback(arg1:string):Promise<void>;

export function SaveConnection(arg1:models.ConnectionConfig):Promise<models.ConnectionConfig>;

export function TestConnection(arg1:models.ConnectionConfig):Promise<string>;
