// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Commit(arg1) {
  return window['go']['main']['App']['Commit'](arg1);
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['main']['App']['Disconnect'](arg1);
}

export function ExecuteSQL(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteSQL'](arg1, arg2, arg3);
}

export function GetActiveConnectionID() {
  return window['go']['main']['App']['GetActiveConnectionID']();
}

export function GetSavedConnections() {
  return window['go']['main']['App']['GetSavedConnections']();
}

export function Rollback(arg1) {
  return window['go']['main']['App']['Rollback'](arg1);
}

export function SaveConnection(arg1) {
  return window['go']['main']['App']['SaveConnection'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}
